"""create_category_fk

Revision ID: 0452a3e35f38
Revises: 7c4709a271cd
Create Date: 2023-12-06 23:58:08.427868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0452a3e35f38'
down_revision: Union[str, None] = '7c4709a271cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'itens', 'category', ['categoria_id'], ['id'])
    op.drop_column('itens', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itens', type_='foreignkey')
    op.drop_column('itens', 'categoria_id')
    # ### end Alembic commands ###
