"""add_categoria

Revision ID: 5e9598666a99
Revises: ef279f4692ef
Create Date: 2023-12-06 22:46:14.746876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9598666a99'
down_revision: Union[str, None] = 'ef279f4692ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens', 'categoria')
    # ### end Alembic commands ###
